name: rise-environment
channels:
  - damianavila82
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - rise
  - jupytext
  - pip:
    - git+https://github.com/rht/py-destilledESL#egg=py-destilledESL
